/* SoC level DTS fixup file */

#define DT_NUM_IRQ_PRIO_BITS	DT_ARM_V7M_NVIC_E000E100_ARM_NUM_IRQ_PRIORITY_BITS

#define DT_CLOCK_CONTROL_BASE_ADDR          DT_TI_STELLARIS_CCM_400FE000_BASE_ADDRESS
#define DT_CLOCK_CONTROL_LABEL              DT_TI_STELLARIS_CCM_400FE000_LABEL
/* End of SoC Level DTS fixup file */
